language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t ijboym216/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true ijboym216/react-test-app npm run test

after_success:
  - docker build -t ijboym216/docker-frontend ./frontend
  - docker build -t ijboym216/docker-backend ./backend
  - docker build -t ijboym216/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push ijboym216/docker-frontend
  - docker push ijboym216/docker-backend
  - docker push ijboym216/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-1-382115335846
  bucket_path: "docker-fullstack-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
